name: Test deploy ios apps
on: 
  workflow_dispatch:
  pull_request:
jobs:
  IOS-Deploy:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      # pull down repository
      # - name: Set up Homebrew
      #   id: set-up-homebrew
      #   uses: Homebrew/actions/setup-homebrew@master
      # - run: brew install base64
      # - run: alias base64=/opt/homebrew/bin/base64
      - name: Pull down repository 
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - run: git branch
      - run: npm ci
      # unlock repository using git crypt secrets
      - uses: flydiverny/setup-git-crypt@v4
      - run:  echo ""$GIT_CRYPT_KEY"" | base64 -Dd -i > ~/key && git-crypt unlock ~/key
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - run: npm run build
      - run: npm test
      - run: npx cap sync ios
      - uses: stefanzweifel/git-auto-commit-action@v5
      - run: npx cap build ios

 
 
