name: Deploy with Github Actions
on: workflow_dispatch
jobs:
  Deploy-Step:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Pull down repository 
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - run: npm install
      - name: Pull down events from Google Sheets
        run: curl --output src/events.csv ""$SUPER_SECRET""
        env:
          SUPER_SECRET: ${{ secrets.GOOGLE_SHEETS_URL }}
      # - name: Deploy with gh-pages
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
