name: Deploy with Github Actions
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Web-Deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # pull down repository and new events
      - name: Pull down repository 
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - run: npm ci
      - run: npm test
      # unlock repository using git crypt secrets
      - uses: flydiverny/setup-git-crypt@v4
      - run:  echo ""$GIT_CRYPT_KEY"" | base64 -di --decode > ~/key && git-crypt unlock ~/key && rm ~/key
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Pull down events from Google Sheets
        run: curl --output src/events.csv ""$SUPER_SECRET""
        env:
          SUPER_SECRET: ${{ secrets.GOOGLE_SHEETS_URL }}
      # commit new events and deploy to website
      - uses: stefanzweifel/git-auto-commit-action@v5
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
  Android-Deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [Web-Deploy]
    steps:
      # pull down repository
      - name: Pull down repository 
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      # set up java and gradle
      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '17'
      # use this webpage to match-up java versions and gradle versions
      # https://docs.gradle.org/current/userguide/compatibility.html
      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"
      # - run: alias gradle='/home/runner/work/_temp/.gradle-actions/gradle-installations/installs/gradle-8.10/bin/gradle'
      # install npm dependencies
      - run: npm ci 
      # unlock repository using git crypt secrets
      - uses: flydiverny/setup-git-crypt@v4
      - run:  echo ""$GIT_CRYPT_KEY"" | base64 -di --decode > ~/key && git-crypt unlock ~/key
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      # refresh build for android, commit
      - run: npm run build
      - run: npm test
      - run: npx cap sync android
      - uses: stefanzweifel/git-auto-commit-action@v5
      # build app and publish as artifact
      - run: npx cap build android --androidreleasetype AAB
      - run: npx cap build android --androidreleasetype APK
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-files
          path: /home/runner/work/touhoufest-webapp/touhoufest-webapp/android/app/build/outputs/bundle/release/
      - name: Upload app to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          packageName: com.touhoufest.touhoufestwebapp
          releaseFiles: /home/runner/work/touhoufest-webapp/touhoufest-webapp/android/app/build/outputs/bundle/release/app-release-signed.aab
          track: alpha
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        
