# note: this workflow is obsolete because netlify already does this,
# but it will be preserved for posterity
name: Netlify Test Deployments for PRs
on: 
  workflow_dispatch:
  pull_request:
jobs:
  Web-Deploy:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      # pull down repository and new events
      - name: Pull down repository to merge of PR
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - run: git pull
      - run: npm ci
      # unlock repository using git crypt secrets
      - uses: flydiverny/setup-git-crypt@v4
      - run:  echo ""$GIT_CRYPT_KEY"" | base64 -di --decode > ~/key && git-crypt unlock ~/key && rm ~/key
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      # - name: Pull down events from Google Sheets
      #   run: curl --output src/events.csv ""$SUPER_SECRET""
      #   env:
      #     SUPER_SECRET: ${{ secrets.GOOGLE_SHEETS_URL }}
      # commit new events and deploy to website
      # - uses: stefanzweifel/git-auto-commit-action@v5
      - uses: nelonoel/branch-name@v1.0.1
      - run: npm run build
      - run: npm test